# Generated by Django 5.0.3 on 2024-06-24 11:19

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forAUTH", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="fullname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ism-familiya"
            ),
        ),
    ]
