# Generated by Django 5.0.3 on 2024-06-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forAUTH", "0002_alter_user_managers_user_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=13, unique=True, verbose_name="Telefon raqam"
            ),
        ),
    ]
